### ISSUE TITLE
Is the "upstream" directory helping this project?

### ISSUE THREAD

**Issue by stevector** [stevector/drupal-9-with-pantheon-orb#7]
When I created this repo I copied from @greg-1-anderson's work on Pantheon's Integrated Composer feature where the `upstream` directory helped separate a generic/git-updatable `composer.json` from the site-specific `composer.json` at the root directory.

For this project though I don't expect people to be doing git merges from this repo into their individual copies. If that's true, the separate `upstream` directory is not adding much value here and the two `composer.json` files should be combined.

**Comment by sugaroverflow** [comment]
Sounds good to me 🚀

**Comment by stevector** [comment]
done here: https://github.com/pantheon-systems/drupal-9-with-circleci-orb/pull/1
